### ISSUE TITLE
Please source code 

### ISSUE THREAD

**Issue by 3dgoose** [Spoovywit/-BASIC-OS#2]

**Comment by Spoovywit** [comment]
Hello! What do you mean by source code? If your talking about where I got
the. Code from, I coded it in either qb64 or 45

**Comment by 3dgoose** [comment]
No, I know, I could even help as I am a QB64 developer myself, but I would like to have to source code of the operating system.

**Comment by Spoovywit** [comment]
im sorry but i am trying to keep all the source code out of the public in
worry of it getting leaked.

**Comment by Spoovywit** [comment]
i want most of it to be kept secret

**Comment by 3dgoose** [comment]
Okay. But the executable is here, I could dump the content :)

**Comment by Spoovywit** [comment]
go ahead all it is right now is a number guessing game,

**Comment by Spoovywit** [comment]
i want to thank you for the offer though

**Comment by Spoovywit** [comment]
there are some other projects you can help me with if you want

**Comment by 3dgoose** [comment]
Yes of course gimme url
